# docker-compose.yml
version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: si-sorting-frontend
    container_name: si-sorting-frontend
    ports:
      - "3000:3000"
    environment:
      DEPLOY_MODE: compose
    volumes:
      - ./frontend:/app

  rest:
    build:
      context: .
      dockerfile: rest/Dockerfile
    image: si-sorting-rest
    container_name: si-sorting-rest
    ports:
      - "5000:5000"
    environment:
      DEPLOY_MODE: compose
    volumes:
      - ./rest:/app
