# docker-compose.yml
version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: si-sorting-frontend
    container_name: si-sorting-frontend
    ports:
      - "3000:3000"
    environment:
      DEPLOY_MODE: compose
    volumes:
      - ./frontend:/app

  rest:
    build:
      context: .
      dockerfile: rest/Dockerfile
    image: si-sorting-rest
    container_name: si-sorting-rest
    ports:
      - "8000:8000"
    environment:
      DEPLOY_MODE: compose
    volumes:
      - ./rest:/app

  worker:
    build:
      context: .
      dockerfile: containers/Dockerfile.combined
    image: si-sorting-worker
    container_name: si-sorting-worker
    environment:
      DEPLOY_MODE: compose
      AWS_REGION_NAME: ${AWS_REGION_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
