name: Build Worker Image and Push to GCR

on:
  push:
    branches:
      - main
    paths:
      - "containers/**"

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build the Docker image
      #   run: |
      #     docker build --tag ghcr.io/catalystneuro/si-sorting-worker:latest -f ./containers/Dockerfile.combined ./containers
      #     docker push ghcr.io/catalystneuro/si-sorting-worker:latest

      - name: Set up Docker Layer Caching
        uses: docker/build-push-action@v2.7.0
        with:
          driver: cache
          target: builder

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./containers
          dockerfile: Dockerfile.combined
          push: true
          tags: ghcr.io/catalystneuro/si-sorting-worker:latest
          cache-from: type=registry,ref=ghcr.io/catalystneuro/si-sorting-worker:latest
