name: Build Worker Image and Push to GCR

on:
  push:
    branches:
      - main
    paths:
      - "containers/**"

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build --tag ghcr.io/catalystneuro/si-sorting-worker:latest -f ./containers/Dockerfile.combined ./containers
          docker push ghcr.io/catalystneuro/si-sorting-worker:latest
